#!/bin/bash 
bcpp -ylcnc -i 3	Stiff_Bulirsch-Stoer.h     CPY/Stiff_Bulirsch-Stoer.h  
bcpp -ylcnc -i 3	break.h                    CPY/break.h                 
bcpp -ylcnc -i 3	display.h                  CPY/display.h               
bcpp -ylcnc -i 3	eos.h                      CPY/eos.h                   
bcpp -ylcnc -i 3	fem_ele.h                  CPY/fem_ele.h               
bcpp -ylcnc -i 3	fem_ele_std.h              CPY/fem_ele_std.h           
bcpp -ylcnc -i 3	fem_ele_vec.h              CPY/fem_ele_vec.h           
bcpp -ylcnc -i 3	FEMEnums.h                 CPY/FEMEnums.h              
bcpp -ylcnc -i 3	femlib.h                   CPY/femlib.h                
bcpp -ylcnc -i 3	files0.h                   CPY/files0.h                
bcpp -ylcnc -i 3	makros.h                   CPY/makros.h                
bcpp -ylcnc -i 3	mathlib.h                  CPY/mathlib.h               
bcpp -ylcnc -i 3	matrix_class.h             CPY/matrix_class.h          
bcpp -ylcnc -i 3	memory.h                   CPY/memory.h                
bcpp -ylcnc -i 3	par_ddc.h                  CPY/par_ddc.h               
bcpp -ylcnc -i 3	pcs_dm.h                   CPY/pcs_dm.h                
bcpp -ylcnc -i 3	problem.h                  CPY/problem.h               
bcpp -ylcnc -i 3	prototyp.h                 CPY/prototyp.h              
bcpp -ylcnc -i 3	rf_bc_new.h                CPY/rf_bc_new.h             
bcpp -ylcnc -i 3	rf_fct.h                   CPY/rf_fct.h                
bcpp -ylcnc -i 3	rf_fluid_momentum.h        CPY/rf_fluid_momentum.h     
bcpp -ylcnc -i 3	rf_ic_new.h                CPY/rf_ic_new.h             
bcpp -ylcnc -i 3	rf_kinreact.h              CPY/rf_kinreact.h           
bcpp -ylcnc -i 3	rf_mfp_new.h               CPY/rf_mfp_new.h            
bcpp -ylcnc -i 3	rf_mmp_new.h               CPY/rf_mmp_new.h            
bcpp -ylcnc -i 3	rf_msp_new.h               CPY/rf_msp_new.h            
bcpp -ylcnc -i 3	rf_node.h                  CPY/rf_node.h               
bcpp -ylcnc -i 3	rf_num_new.h               CPY/rf_num_new.h            
bcpp -ylcnc -i 3	rf_out_new.h               CPY/rf_out_new.h            
bcpp -ylcnc -i 3	rf_pcs.h                   CPY/rf_pcs.h                
bcpp -ylcnc -i 3	rf_random_walk.h           CPY/rf_random_walk.h        
bcpp -ylcnc -i 3	rf_react.h                 CPY/rf_react.h              
bcpp -ylcnc -i 3	rf_st_new.h                CPY/rf_st_new.h             
bcpp -ylcnc -i 3	rf_tim_new.h               CPY/rf_tim_new.h            
bcpp -ylcnc -i 3	rfmat_cp.h                 CPY/rfmat_cp.h              
bcpp -ylcnc -i 3	solver.h                   CPY/solver.h                
bcpp -ylcnc -i 3	timer.h                    CPY/timer.h                 
bcpp -ylcnc -i 3	tools.h                    CPY/tools.h                 
bcpp -ylcnc -i 3	vtk.h                      CPY/vtk.h                   
bcpp -ylcnc -i 3	GeoInfo.h                  CPY/GeoInfo.h               
bcpp -ylcnc -i 3	ProcessInfo.h              CPY/ProcessInfo.h           
bcpp -ylcnc -i 3	DistributionInfo.h         CPY/DistributionInfo.h      
bcpp -ylcnc -i 3	GeoInfo.cpp                CPY/GeoInfo.cpp             
bcpp -ylcnc -i 3	ProcessInfo.cpp            CPY/ProcessInfo.cpp         
bcpp -ylcnc -i 3	DistributionInfo.cpp       CPY/DistributionInfo.cpp    
bcpp -ylcnc -i 3	Stiff_Bulirsch-Stoer.cpp   CPY/Stiff_Bulirsch-Stoer.cpp
bcpp -ylcnc -i 3	break.cpp                  CPY/break.cpp               
bcpp -ylcnc -i 3	display.cpp                CPY/display.cpp             
bcpp -ylcnc -i 3	eos.cpp                    CPY/eos.cpp                 
bcpp -ylcnc -i 3	fem_ele.cpp                CPY/fem_ele.cpp             
bcpp -ylcnc -i 3	fem_ele_std.cpp            CPY/fem_ele_std.cpp         
bcpp -ylcnc -i 3	fem_ele_vec.cpp            CPY/fem_ele_vec.cpp         
bcpp -ylcnc -i 3	femlib.cpp                 CPY/femlib.cpp              
bcpp -ylcnc -i 3	FEMEnums.cpp               CPY/FEMEnums.cpp            
bcpp -ylcnc -i 3	files0.cpp                 CPY/files0.cpp              
bcpp -ylcnc -i 3	mathlib.cpp                CPY/mathlib.cpp             
bcpp -ylcnc -i 3	matrix_class.cpp           CPY/matrix_class.cpp        
bcpp -ylcnc -i 3	memory.cpp                 CPY/memory.cpp              
bcpp -ylcnc -i 3	par_ddc.cpp                CPY/par_ddc.cpp             
bcpp -ylcnc -i 3	pcs_dm.cpp                 CPY/pcs_dm.cpp              
bcpp -ylcnc -i 3	problem.cpp                CPY/problem.cpp             
bcpp -ylcnc -i 3	rf_bc_new.cpp              CPY/rf_bc_new.cpp           
bcpp -ylcnc -i 3	rf_fct.cpp                 CPY/rf_fct.cpp              
bcpp -ylcnc -i 3	rf_fluid_momentum.cpp      CPY/rf_fluid_momentum.cpp   
bcpp -ylcnc -i 3	rf_ic_new.cpp              CPY/rf_ic_new.cpp           
bcpp -ylcnc -i 3	rf_kinreact.cpp            CPY/rf_kinreact.cpp         
bcpp -ylcnc -i 3	rf_mfp_new.cpp             CPY/rf_mfp_new.cpp          
bcpp -ylcnc -i 3	rf_mmp_new.cpp             CPY/rf_mmp_new.cpp          
bcpp -ylcnc -i 3	rf_msp_new.cpp             CPY/rf_msp_new.cpp          
bcpp -ylcnc -i 3	rf_node.cpp                CPY/rf_node.cpp             
bcpp -ylcnc -i 3	rf_num_new.cpp             CPY/rf_num_new.cpp          
bcpp -ylcnc -i 3	rf_out_new.cpp             CPY/rf_out_new.cpp          
bcpp -ylcnc -i 3	rf_pcs.cpp                 CPY/rf_pcs.cpp              
bcpp -ylcnc -i 3	rf_random_walk.cpp         CPY/rf_random_walk.cpp      
bcpp -ylcnc -i 3	rf_react.cpp               CPY/rf_react.cpp            
bcpp -ylcnc -i 3	rf_st_new.cpp              CPY/rf_st_new.cpp           
bcpp -ylcnc -i 3	rf_tim_new.cpp             CPY/rf_tim_new.cpp          
bcpp -ylcnc -i 3	rfmat_cp.cpp	           CPY/rfmat_cp.cpp	           
bcpp -ylcnc -i 3	timer.cpp                  CPY/timer.cpp               
bcpp -ylcnc -i 3	tools.cpp                  CPY/tools.cpp               
bcpp -ylcnc -i 3	vtk.cpp                    CPY/vtk.cpp                 
bcpp -ylcnc -i 3	equation_class.cpp         CPY/equation_class.cpp
bcpp -ylcnc -i 3	equation_class.h           CPY/equation_class.h
bcpp -ylcnc -i 3	intrface.cpp               CPY/intrface.cpp
bcpp -ylcnc -i 3	intrface.h                 CPY/intrface.h
bcpp -ylcnc -i 3	matrix.cpp                 CPY/matrix.cpp       
bcpp -ylcnc -i 3	matrix.h                   CPY/matrix.h         
bcpp -ylcnc -i 3	solver.cpp                 CPY/solver.cpp       
bcpp -ylcnc -i 3	rf_REACT_BRNS.cpp          CPY/rf_REACT_BRNS.cpp
bcpp -ylcnc -i 3	rf_REACT_BRNS.h            CPY/rf_REACT_BRNS.h  
bcpp -ylcnc -i 3	rf_REACT_GEM.cpp           CPY/rf_REACT_GEM.cpp 
bcpp -ylcnc -i 3	rf_REACT_GEM.h             CPY/rf_REACT_GEM.h   
