## MDL: cmake options for compiling ogs with LIBPHREEQC

message (STATUS "Configuration: g++ and LIBPHREEQC")

ADD_DEFINITIONS(-D_POSIX_SOURCE)
ADD_DEFINITIONS(-DNO_ERROR_CONTROL)
ADD_DEFINITIONS(-DNEW_EQS)

IF(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_COMPILER_IS_GNUCC)  #WW
	IF (LIBPQC_DEBUG)
		MESSAGE (STATUS  "Compiling ogs and LIBPHREEQC with debug flags" )
		SET(CMAKE_CXX_FLAGS "-O0 -ggdb -Wall")
	ELSE (LIBPQC_DEBUG)
		ADD_DEFINITIONS ( "-O3" )
	ENDIF (LIBPQC_DEBUG)
ENDIF(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_COMPILER_IS_GNUCC)

set (LIBPQC ON)

##ADD_DEFINITIONS ( -DLIBPHREEQC )


