ADD_DEFINITIONS(-DNEW_EQS)
ADD_DEFINITIONS(-DBRNS)
ADD_DEFINITIONS(-DNO_ERROR_CONTROL)
ADD_DEFINITIONS(-D_POSIX_SOURCE)


IF(PARALLEL_USE_MPI)
		ADD_DEFINITIONS(-DUSE_MPI_BRNS)
ENDIF(PARALLEL_USE_MPI)

